events{
    multi_accept on;    # Allows multiple connections to be accepted at the same time
    accept_mutex on;    # Ensures only 1 process accepts connections at a time
}

http{
    upstream dockerproject {
        server web:5000;
    }
    server{
        listen 80;
        location / {
            proxy_pass http://dockerproject;
        }
    }

}

