name: Deploy to S3

on:
  push:
    branches: [ main ]                # When: run every time you push to main
    paths:
      - '06-aws/projects/assignment-3-s3-cloudfront-cdn-route53/**'

permissions:
  id-token: write                     # Lets the job prove it's identity to AWS via OIDC
  contents: read                      # Lets the job read your reop's files

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4     # Copy repo onto the machine

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}   # Borrow your AWS role
          aws-region: eu-west-2
        
      - name: Upload site to S3
        run: aws s3 sync ./06-aws/projects/assignment-3-s3-cloudfront-cdn-route53/sites s3://a3-biram-s3 --delete   # Copy files to the bucket

      - name: Refresh CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"  # Clear the cache